import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Redis Cache Demo Next App",
  description: "Generated by Eddy Lee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
